-- Outbox persistente para entregas WhatsApp de resultados, premios y jugadas.
-- Evita perder una notificación si Supabase guarda el resultado pero el proceso
-- se reinicia antes de que Baileys consiga enviarlo.

create table if not exists public.whatsapp_notificaciones_outbox (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('resultado','premio','jugada')),
  referencia_id text not null,
  destino_id text not null,
  texto text not null,
  etiqueta text,
  estado text not null default 'pendiente' check (estado in ('pendiente','enviado')),
  intentos integer not null default 0,
  ultimo_error text,
  creado_at timestamptz not null default now(),
  ultimo_intento_at timestamptz,
  enviado_at timestamptz
);

create unique index if not exists whatsapp_notificaciones_outbox_unq
  on public.whatsapp_notificaciones_outbox (tipo, referencia_id, destino_id);

create index if not exists whatsapp_notificaciones_outbox_pendientes_idx
  on public.whatsapp_notificaciones_outbox (estado, creado_at);

alter table public.whatsapp_notificaciones_outbox enable row level security;

revoke all on public.whatsapp_notificaciones_outbox from anon, authenticated;
grant select, insert, update on public.whatsapp_notificaciones_outbox to service_role;
grant usage, select on sequence public.whatsapp_notificaciones_outbox_id_seq to service_role;
