-- WhatsApp independiente por comercial.
-- Cada comercial tiene una única sesión Baileys persistida en Supabase.
create table if not exists public.whatsapp_comercial_session (
  comercial_telegram_id bigint primary key references public.users(telegram_id) on delete cascade,
  creds jsonb,
  keys jsonb,
  estado text not null default 'desconectado'
    check (estado in ('desconectado','esperando_qr','conectando','conectado')),
  telefono text,
  ultimo_qr text,
  ultimo_error text,
  ultimo_mensaje_at timestamptz,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.whatsapp_comercial_session enable row level security;

create index if not exists idx_whatsapp_comercial_estado
  on public.whatsapp_comercial_session (estado);

create table if not exists public.whatsapp_inbox (
  id bigint generated by default as identity primary key,
  comercial_telegram_id bigint not null references public.users(telegram_id) on delete cascade,
  message_id text not null,
  remote_jid text not null,
  sender_jid text,
  sender_name text,
  texto text not null,
  recibido_at timestamptz not null default now(),
  procesado boolean not null default false,
  bet_ids bigint[] default '{}',
  error text,
  unique (comercial_telegram_id, message_id)
);

alter table public.whatsapp_inbox enable row level security;
create index if not exists idx_whatsapp_inbox_comercial_fecha
  on public.whatsapp_inbox (comercial_telegram_id, recibido_at desc);

-- Vincula opcionalmente el cliente de banca con su JID de WhatsApp.
alter table public.clientes_banca
  add column if not exists whatsapp_jid text;

create unique index if not exists uq_clientes_banca_whatsapp_jid
  on public.clientes_banca (comercial_telegram_id, whatsapp_jid)
  where whatsapp_jid is not null;
