-- Migración: múltiples cuentas WhatsApp por un mismo comercial de Telegram.
-- Ejecutar UNA sola vez en Supabase SQL Editor antes de usar:
--   /wa_conectar secundaria
--
-- La cuenta existente NO se mueve ni se toca: permanece en
-- whatsapp_comercial_session como cuenta "principal".
-- Las cuentas adicionales guardan sus creds/keys en filas independientes.

create table if not exists public.whatsapp_comercial_cuentas (
  id bigint generated by default as identity primary key,
  comercial_telegram_id bigint not null,
  alias text not null,
  estado text not null default 'desconectado',
  telefono text,
  creds jsonb,
  keys jsonb,
  ultimo_qr text,
  ultimo_error text,
  ultimo_mensaje_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint whatsapp_comercial_cuentas_alias_chk
    check (alias ~ '^[a-z0-9_-]{1,32}$'),
  constraint whatsapp_comercial_cuentas_unique_alias
    unique (comercial_telegram_id, alias)
);

create index if not exists idx_whatsapp_comercial_cuentas_comercial
  on public.whatsapp_comercial_cuentas (comercial_telegram_id);

-- El módulo de estadísticas necesita distinguir el canal asociado a cada
-- cuenta WhatsApp. Las filas antiguas quedan automáticamente como "principal".
alter table public.whatsapp_estadisticas_canales
  add column if not exists cuenta_alias text not null default 'principal';

create unique index if not exists uq_whatsapp_estadisticas_canales_comercial_cuenta
  on public.whatsapp_estadisticas_canales (comercial_telegram_id, cuenta_alias);

-- La sesión principal sigue usando la tabla histórica y no se modifica.


-- La cola de estadísticas también debe separar las entregas por cuenta.
alter table public.whatsapp_estadisticas_outbox
  add column if not exists cuenta_alias text not null default 'principal';

-- El esquema anterior podía tener una unicidad solo por comercial.
-- La eliminamos para permitir un canal independiente por cada cuenta.
do $$
declare
  r record;
begin
  for r in
    select c.conname
    from pg_constraint c
    join pg_class t on t.oid = c.conrelid
    join pg_namespace n on n.oid = t.relnamespace
    where n.nspname = 'public'
      and t.relname = 'whatsapp_estadisticas_canales'
      and c.contype = 'u'
      and (
        select array_agg(a.attname::text order by a.attname::text)
        from pg_attribute a
        where a.attrelid = c.conrelid
          and a.attnum = any(c.conkey)
      ) = array['comercial_telegram_id']::text[]
  loop
    execute format('alter table public.whatsapp_estadisticas_canales drop constraint %I', r.conname);
  end loop;
end $$;

do $$
declare
  r record;
begin
  for r in
    select c.conname
    from pg_constraint c
    join pg_class t on t.oid = c.conrelid
    join pg_namespace n on n.oid = t.relnamespace
    where n.nspname = 'public'
      and t.relname = 'whatsapp_estadisticas_outbox'
      and c.contype = 'u'
      and (
        select array_agg(a.attname order by a.attname)
        from pg_attribute a
        where a.attrelid = c.conrelid
          and a.attnum = any(c.conkey)
      ) = array['comercial_telegram_id','post_id']::text[]
  loop
    execute format('alter table public.whatsapp_estadisticas_outbox drop constraint %I', r.conname);
  end loop;
end $$;

create unique index if not exists uq_whatsapp_estadisticas_canales_comercial_cuenta
  on public.whatsapp_estadisticas_canales (comercial_telegram_id, cuenta_alias);

-- También eliminamos índices UNIQUE antiguos que no estén respaldados por una constraint.
-- Esto evita que un índice histórico (post_id, comercial_telegram_id) siga
-- impidiendo una segunda cuenta para el mismo comercial.
do $
declare
  r record;
begin
  for r in
    select i.indexrelid::regclass::text as index_name
    from pg_index i
    join pg_class t on t.oid = i.indrelid
    join pg_namespace n on n.oid = t.relnamespace
    where n.nspname = 'public'
      and i.indisunique
      and not i.indisprimary
      and t.relname = 'whatsapp_estadisticas_canales'
      and i.indexrelid::regclass::text <> 'public.uq_whatsapp_estadisticas_canales_comercial_cuenta'
      and (
        select array_agg(a.attname::text order by a.attname::text)
        from pg_attribute a
        where a.attrelid = i.indrelid
          and a.attnum = any(i.indkey)
          and a.attnum > 0
      ) = array['comercial_telegram_id']::text[]
  loop
    execute 'drop index if exists ' || r.index_name;
  end loop;
end $;

do $
declare
  r record;
begin
  for r in
    select i.indexrelid::regclass::text as index_name
    from pg_index i
    join pg_class t on t.oid = i.indrelid
    join pg_namespace n on n.oid = t.relnamespace
    where n.nspname = 'public'
      and i.indisunique
      and not i.indisprimary
      and t.relname = 'whatsapp_estadisticas_outbox'
      and i.indexrelid::regclass::text <> 'public.uq_whatsapp_estadisticas_outbox_post_comercial_cuenta'
      and (
        select array_agg(a.attname::text order by a.attname::text)
        from pg_attribute a
        where a.attrelid = i.indrelid
          and a.attnum = any(i.indkey)
          and a.attnum > 0
      ) = array['comercial_telegram_id','post_id']::text[]
  loop
    execute 'drop index if exists ' || r.index_name;
  end loop;
end $;

create unique index if not exists uq_whatsapp_estadisticas_outbox_post_comercial_cuenta
  on public.whatsapp_estadisticas_outbox (post_id, comercial_telegram_id, cuenta_alias);
