-- Migración: múltiples cuentas WhatsApp por un mismo comercial de Telegram.
-- Ejecutar UNA sola vez en Supabase SQL Editor antes de usar:
--   /wa_conectar secundaria
--
-- La cuenta existente NO se mueve ni se toca: permanece en
-- whatsapp_comercial_session como cuenta "principal".
-- Las cuentas adicionales guardan sus creds/keys en filas independientes.

create table if not exists public.whatsapp_comercial_cuentas (
  id bigint generated by default as identity primary key,
  comercial_telegram_id bigint not null,
  alias text not null,
  estado text not null default 'desconectado',
  telefono text,
  creds jsonb,
  keys jsonb,
  ultimo_qr text,
  ultimo_error text,
  ultimo_mensaje_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint whatsapp_comercial_cuentas_alias_chk
    check (alias ~ '^[a-z0-9_-]{1,32}$'),
  constraint whatsapp_comercial_cuentas_unique_alias
    unique (comercial_telegram_id, alias)
);

create index if not exists idx_whatsapp_comercial_cuentas_comercial
  on public.whatsapp_comercial_cuentas (comercial_telegram_id);

-- El módulo de estadísticas necesita distinguir el canal asociado a cada
-- cuenta WhatsApp. Las filas antiguas quedan automáticamente como "principal".
alter table public.whatsapp_estadisticas_canales
  add column if not exists cuenta_alias text not null default 'principal';

create unique index if not exists uq_whatsapp_estadisticas_canales_comercial_cuenta
  on public.whatsapp_estadisticas_canales (comercial_telegram_id, cuenta_alias);

-- La sesión principal sigue usando la tabla histórica y no se modifica.
