-- Feed central de jugadas procesadas.
-- El bot sigue siendo el responsable de interpretar/calcular la jugada.
-- Este trigger crea el evento automáticamente cuando bets queda registrada.

create table if not exists public.jugadas_eventos (
  id bigint generated by default as identity primary key,
  bet_id bigint not null,
  origen text not null default 'telegram',
  loteria_id bigint,
  sorteo_id bigint,
  fecha_apuesta date,
  jugador_nombre text,
  user_telegram_id bigint,
  comercial_telegram_id bigint,
  cliente_banca_id bigint,
  total_apuesta numeric(14,2) not null default 0,
  moneda text not null default 'cup',
  input_raw text,
  detalle jsonb,
  creado_en timestamptz not null default now(),
  entregado_whatsapp boolean not null default false,
  entregado_app boolean not null default false,
  unique (bet_id)
);

create index if not exists idx_jugadas_eventos_creado_en
  on public.jugadas_eventos (creado_en desc);

create index if not exists idx_jugadas_eventos_fecha
  on public.jugadas_eventos (fecha_apuesta);

create index if not exists idx_jugadas_eventos_sorteo
  on public.jugadas_eventos (loteria_id, sorteo_id, fecha_apuesta);

alter table public.jugadas_eventos enable row level security;

-- No se concede lectura pública. La aplicación deberá autenticarse y recibir
-- una política específica cuando definamos su modelo de usuarios/permisos.

create or replace function public.crear_jugada_evento()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  detalle_json jsonb;
  nombre_jugador text := null;
  cliente_nombre text := null;
begin
  begin
    detalle_json := coalesce(nullif(new.detalle, '')::jsonb, '[]'::jsonb);
  exception when others then
    detalle_json := '[]'::jsonb;
  end;

  -- Para apuestas comerciales, el nombre real del jugador vive en
  -- clientes_banca y no debe confundirse con user_telegram_id.
  if new.cliente_banca_id is not null then
    select cb.nombre into cliente_nombre
    from public.clientes_banca cb
    where cb.id = new.cliente_banca_id
    limit 1;
    nombre_jugador := cliente_nombre;
  end if;

  insert into public.jugadas_eventos (
    bet_id,
    origen,
    loteria_id,
    sorteo_id,
    fecha_apuesta,
    jugador_nombre,
    user_telegram_id,
    comercial_telegram_id,
    cliente_banca_id,
    total_apuesta,
    moneda,
    input_raw,
    detalle
  ) values (
    new.id,
    coalesce(new.origen, 'telegram'),
    new.loteria_id,
    new.sorteo_id,
    new.fecha_apuesta,
    nombre_jugador,
    new.user_telegram_id,
    new.comercial_telegram_id,
    new.cliente_banca_id,
    coalesce(new.total_apuesta, 0),
    coalesce(new.moneda, 'cup'),
    new.input_raw,
    detalle_json
  )
  on conflict (bet_id) do nothing;

  return new;
end;
$$;

drop trigger if exists trg_bets_crear_jugada_evento on public.bets;

create trigger trg_bets_crear_jugada_evento
after insert on public.bets
for each row
execute function public.crear_jugada_evento();

-- Habilitar Realtime para que una futura aplicación pueda recibir nuevas
-- jugadas sin hacer polling. Si la tabla ya pertenece a la publicación,
-- PostgreSQL rechazará el ALTER; por eso se ejecuta dentro de un bloque.
do $$
begin
  begin
    alter publication supabase_realtime add table public.jugadas_eventos;
  exception
    when duplicate_object then null;
    when undefined_object then null;
  end;
end;
$$;
