create table if not exists public.pending_bets (
  id bigint generated by default as identity primary key,
  user_telegram_id bigint not null,
  chat_id bigint not null,
  loteria_id bigint not null,
  sorteo_id bigint not null,
  moneda text not null default 'cup',
  original_input text not null,
  ambiguous_numbers text[] not null default '{}',
  corrected_input text,
  status text not null default 'pending' check (status in ('pending','approved','processed','rejected','error')),
  reviewed_by bigint,
  reviewed_at timestamptz,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists pending_bets_user_status_idx
  on public.pending_bets(user_telegram_id, status, created_at desc);

create index if not exists pending_bets_status_idx
  on public.pending_bets(status, created_at asc);

create unique index if not exists pending_bets_one_pending_per_user_idx
  on public.pending_bets(user_telegram_id)
  where status = 'pending';

revoke all on table public.pending_bets from public;
grant all on table public.pending_bets to service_role;
