-- Módulo comercial de estadísticas WhatsApp, independiente de resultados/premios.
create table if not exists public.whatsapp_estadisticas_modulo (
  comercial_telegram_id bigint primary key,
  habilitado boolean not null default false,
  fecha_inicio timestamptz null,
  fecha_vencimiento timestamptz null,
  actualizado_por bigint null,
  updated_at timestamptz not null default now()
);
create index if not exists idx_whatsapp_estadisticas_modulo_activo on public.whatsapp_estadisticas_modulo (habilitado, fecha_vencimiento);

create table if not exists public.whatsapp_estadisticas_posts (
  id bigint generated by default as identity primary key,
  telegram_chat_id text not null,
  telegram_message_id bigint not null,
  fecha_publicacion timestamptz not null,
  fecha_cuba date not null,
  texto text not null default '',
  enlace_telegram text null,
  tipo text not null default 'texto',
  creado_at timestamptz not null default now(),
  unique (telegram_chat_id, telegram_message_id)
);
create index if not exists idx_whatsapp_estadisticas_posts_fecha on public.whatsapp_estadisticas_posts (fecha_cuba, telegram_message_id);

create table if not exists public.whatsapp_estadisticas_outbox (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.whatsapp_estadisticas_posts(id) on delete cascade,
  comercial_telegram_id bigint not null,
  destino_id text not null,
  estado text not null default 'pendiente' check (estado in ('pendiente','enviando','enviado','error','omitido')),
  intentos integer not null default 0,
  ultimo_error text null,
  ultimo_intento_at timestamptz null,
  enviado_at timestamptz null,
  creado_at timestamptz not null default now(),
  unique (post_id, comercial_telegram_id)
);
create index if not exists idx_whatsapp_estadisticas_outbox_pendiente on public.whatsapp_estadisticas_outbox (estado, creado_at);

comment on table public.whatsapp_estadisticas_modulo is 'Suscripción independiente y de pago para recibir publicaciones del canal de estadísticas.';
comment on table public.whatsapp_estadisticas_posts is 'Publicaciones capturadas diariamente desde el canal Telegram de estadísticas.';
comment on table public.whatsapp_estadisticas_outbox is 'Cola idempotente de entrega de estadísticas a los grupos de cada comercial.';