-- LotoPro Parser - Modalidad "Comercial" + gestión de premios/depósitos
-- Agrega:
--   1) rol de usuario (cliente | comercial | admin)
--   2) clientes_banca: jugadores del comercial sin cuenta Telegram, con saldo a favor
--   3) columnas en bets para distinguir origen (app vs comercial)
--   4) resultados_sorteo: números ganadores por sorteo/fecha
--   5) premios: detección de jugadas ganadoras y su resolución (cobrado/depositado)
--
-- Safe to run more than once.

begin;

-- ---------------------------------------------------------------------------
-- 1) ROL DE USUARIO
-- ---------------------------------------------------------------------------
alter table public.users
  add column if not exists role text not null default 'cliente';

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'users_role_check'
  ) then
    alter table public.users
      add constraint users_role_check check (role in ('cliente', 'comercial', 'admin'));
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 2) CLIENTES DE BANCA (jugadores del comercial, identificados solo por nombre)
--    Acumulan saldo a favor cuando un premio se deja "como depósito" en vez
--    de cobrarse en efectivo. Ese saldo puede usarse como crédito en la
--    siguiente jugada que el comercial le anote.
-- ---------------------------------------------------------------------------
create table if not exists public.clientes_banca (
  id bigint generated by default as identity primary key,
  comercial_telegram_id bigint not null,
  nombre text not null,
  saldo numeric(14,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint clientes_banca_comercial_fk
    foreign key (comercial_telegram_id)
    references public.users(telegram_id)
    on update cascade
    on delete cascade,
  constraint clientes_banca_saldo_nonnegative check (saldo >= 0),
  constraint clientes_banca_unique unique (comercial_telegram_id, nombre)
);

create index if not exists idx_clientes_banca_comercial
  on public.clientes_banca (comercial_telegram_id);

drop trigger if exists trg_clientes_banca_updated_at on public.clientes_banca;
create trigger trg_clientes_banca_updated_at
before update on public.clientes_banca
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- 3) BETS: origen de la jugada
-- ---------------------------------------------------------------------------
alter table public.bets
  add column if not exists origen text not null default 'app',
  add column if not exists comercial_telegram_id bigint,
  add column if not exists cliente_banca_id bigint;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'bets_origen_check') then
    alter table public.bets
      add constraint bets_origen_check check (origen in ('app', 'comercial'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'bets_comercial_fk') then
    alter table public.bets
      add constraint bets_comercial_fk
      foreign key (comercial_telegram_id)
      references public.users(telegram_id)
      on update cascade
      on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'bets_cliente_banca_fk') then
    alter table public.bets
      add constraint bets_cliente_banca_fk
      foreign key (cliente_banca_id)
      references public.clientes_banca(id)
      on update cascade
      on delete set null;
  end if;
end $$;

create index if not exists idx_bets_cliente_banca
  on public.bets (cliente_banca_id);

create index if not exists idx_bets_comercial
  on public.bets (comercial_telegram_id, fecha_apuesta);

-- ---------------------------------------------------------------------------
-- 4) RESULTADOS DE SORTEO
--    numero_ganado: {"fijo": "23", "corrido": "45", "centena": "823"}
--    fuente: 'manual' hoy; 'bot_externo' cuando se conecte el bot que da
--    resultados (no requiere cambios de esquema, solo cambiar quién inserta).
-- ---------------------------------------------------------------------------
create table if not exists public.resultados_sorteo (
  id bigint generated by default as identity primary key,
  loteria_id bigint not null,
  sorteo_id bigint not null,
  fecha date not null,
  numero_ganado jsonb not null,
  fuente text not null default 'manual',
  registrado_por bigint,
  created_at timestamptz not null default now(),
  constraint resultados_sorteo_loteria_fk
    foreign key (loteria_id) references public.loterias(id)
    on update cascade on delete cascade,
  constraint resultados_sorteo_sorteo_fk
    foreign key (sorteo_id) references public.sorteos(id)
    on update cascade on delete cascade,
  constraint resultados_sorteo_registrador_fk
    foreign key (registrado_por) references public.users(telegram_id)
    on update cascade on delete set null,
  constraint resultados_sorteo_unique unique (loteria_id, sorteo_id, fecha)
);

create index if not exists idx_resultados_sorteo_fecha
  on public.resultados_sorteo (loteria_id, sorteo_id, fecha);

-- ---------------------------------------------------------------------------
-- 5) PREMIOS
--    estado:
--      detectado  -> el sistema encontró coincidencia con el resultado
--      confirmado -> un humano confirmó el monto del premio
--      cobrado    -> el cliente lo cobró en efectivo (no toca saldo)
--      depositado -> el cliente lo dejó como depósito (se acredita saldo)
--
--    monto_premio queda NULL hasta que un admin/comercial lo confirme,
--    porque el pago por tipo de jugada depende de la comisión/tablas de
--    pago propias de cada banco y no se puede inferir automáticamente.
-- ---------------------------------------------------------------------------
create table if not exists public.premios (
  id bigint generated by default as identity primary key,
  bet_id bigint not null,
  resultado_id bigint not null,
  numeros_ganadores text not null,
  tipo_jugada text not null,
  monto_apostado numeric(14,2) not null,
  monto_premio numeric(14,2),
  estado text not null default 'detectado',
  resuelto_por bigint,
  fecha_resuelto timestamptz,
  created_at timestamptz not null default now(),
  constraint premios_bet_fk
    foreign key (bet_id) references public.bets(id)
    on update cascade on delete cascade,
  constraint premios_resultado_fk
    foreign key (resultado_id) references public.resultados_sorteo(id)
    on update cascade on delete cascade,
  constraint premios_resuelto_por_fk
    foreign key (resuelto_por) references public.users(telegram_id)
    on update cascade on delete set null,
  constraint premios_estado_check
    check (estado in ('detectado', 'confirmado', 'cobrado', 'depositado'))
);

create index if not exists idx_premios_estado on public.premios (estado);
create index if not exists idx_premios_bet on public.premios (bet_id);
create index if not exists idx_premios_resultado on public.premios (resultado_id);

commit;
