-- LotoPro Parser - Supabase database migration
-- Creates the tables required by index.js when they do not exist.
-- Safe to run more than once.
--
-- IMPORTANT:
-- A Supabase project already provides the PostgreSQL database itself.
-- This migration creates/repairs the required schema inside that database;
-- it does not CREATE DATABASE because Supabase migrations run inside the
-- project's existing database.

begin;

-- ---------------------------------------------------------------------------
-- Helper: updated_at trigger
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- USERS
-- Used by getOrCreateUser(), updateUserSaldo(), approveDeposit() and /saldo.
-- telegram_id is the business key used throughout the bot.
-- ---------------------------------------------------------------------------
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null unique,
  username text,
  first_name text,
  saldo numeric(14,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint users_saldo_nonnegative check (saldo >= 0)
);

create index if not exists idx_users_username
  on public.users (username);

-- ---------------------------------------------------------------------------
-- LOTERIAS
-- Catalog used by getLoterias().
-- ---------------------------------------------------------------------------
create table if not exists public.loterias (
  id bigint generated by default as identity primary key,
  nombre text not null,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- SORTEOS
-- Catalog used by getSorteos(), validarHorarioSorteo() and isBetEditable().
-- ---------------------------------------------------------------------------
create table if not exists public.sorteos (
  id bigint generated by default as identity primary key,
  loteria_id bigint not null,
  nombre text not null,
  hora_apertura time,
  hora_cierre time,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sorteos_loteria_fk
    foreign key (loteria_id)
    references public.loterias(id)
    on update cascade
    on delete cascade
);

create index if not exists idx_sorteos_loteria_id
  on public.sorteos (loteria_id);

create index if not exists idx_sorteos_activo_hora
  on public.sorteos (activo, hora_apertura);

-- ---------------------------------------------------------------------------
-- USER PREFERENCES
-- Used by getUserPreference() and saveUserPreference().
-- telegram_id is unique because upsert uses onConflict: telegram_id.
-- ---------------------------------------------------------------------------
create table if not exists public.user_preferences (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null unique,
  loteria_id bigint,
  sorteo_id bigint,
  moneda text not null default 'cup',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_preferences_user_fk
    foreign key (telegram_id)
    references public.users(telegram_id)
    on update cascade
    on delete cascade,
  constraint user_preferences_loteria_fk
    foreign key (loteria_id)
    references public.loterias(id)
    on update cascade
    on delete set null,
  constraint user_preferences_sorteo_fk
    foreign key (sorteo_id)
    references public.sorteos(id)
    on update cascade
    on delete set null
);

create index if not exists idx_user_preferences_loteria_id
  on public.user_preferences (loteria_id);

create index if not exists idx_user_preferences_sorteo_id
  on public.user_preferences (sorteo_id);

-- ---------------------------------------------------------------------------
-- BETS
-- Used by saveBet(), getAcumuladoPorNumero(), getUserBets() and the
-- relation bets -> sorteos used in the bot.
-- ---------------------------------------------------------------------------
create table if not exists public.bets (
  id bigint generated by default as identity primary key,
  user_telegram_id bigint not null,
  loteria_id bigint not null,
  sorteo_id bigint not null,
  fecha_apuesta date not null,
  input_raw text not null,
  total_apuesta numeric(14,2) not null default 0,
  detalle text not null,
  saldo_antes numeric(14,2) not null default 0,
  saldo_despues numeric(14,2) not null default 0,
  moneda text not null default 'cup',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bets_user_fk
    foreign key (user_telegram_id)
    references public.users(telegram_id)
    on update cascade
    on delete restrict,
  constraint bets_loteria_fk
    foreign key (loteria_id)
    references public.loterias(id)
    on update cascade
    on delete restrict,
  constraint bets_sorteo_fk
    foreign key (sorteo_id)
    references public.sorteos(id)
    on update cascade
    on delete restrict
);

create index if not exists idx_bets_user_created
  on public.bets (user_telegram_id, created_at desc);

create index if not exists idx_bets_loteria_sorteo_fecha
  on public.bets (loteria_id, sorteo_id, fecha_apuesta);

create index if not exists idx_bets_sorteo_id
  on public.bets (sorteo_id);

-- ---------------------------------------------------------------------------
-- DEPOSIT REQUESTS
-- Used by createDepositRequest(), approveDeposit() and rejectDeposit().
-- ---------------------------------------------------------------------------
create table if not exists public.deposit_requests (
  id bigint generated by default as identity primary key,
  user_telegram_id bigint not null,
  amount numeric(14,2) not null,
  payment_method text not null,
  proof_file_id text,
  status text not null default 'pending',
  admin_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint deposit_requests_user_fk
    foreign key (user_telegram_id)
    references public.users(telegram_id)
    on update cascade
    on delete restrict,
  constraint deposit_requests_amount_positive
    check (amount > 0),
  constraint deposit_requests_status_check
    check (status in ('pending', 'approved', 'rejected'))
);

create index if not exists idx_deposit_requests_user
  on public.deposit_requests (user_telegram_id, created_at desc);

create index if not exists idx_deposit_requests_status
  on public.deposit_requests (status, created_at desc);

-- ---------------------------------------------------------------------------
-- LIMITS
-- Used by getLimitesGlobales().
-- A NULL loteria_id/sorteo_id means a global rule.
-- ---------------------------------------------------------------------------
create table if not exists public.limits (
  id bigint generated by default as identity primary key,
  loteria_id bigint,
  sorteo_id bigint,
  tipo text not null,
  monto_maximo numeric(14,2) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint limits_loteria_fk
    foreign key (loteria_id)
    references public.loterias(id)
    on update cascade
    on delete cascade,
  constraint limits_sorteo_fk
    foreign key (sorteo_id)
    references public.sorteos(id)
    on update cascade
    on delete cascade,
  constraint limits_monto_positive
    check (monto_maximo >= 0)
);

create index if not exists idx_limits_loteria_sorteo
  on public.limits (loteria_id, sorteo_id);

create index if not exists idx_limits_tipo
  on public.limits (tipo);

-- ---------------------------------------------------------------------------
-- Updated-at triggers
-- ---------------------------------------------------------------------------
drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists trg_loterias_updated_at on public.loterias;
create trigger trg_loterias_updated_at
before update on public.loterias
for each row execute function public.set_updated_at();

drop trigger if exists trg_sorteos_updated_at on public.sorteos;
create trigger trg_sorteos_updated_at
before update on public.sorteos
for each row execute function public.set_updated_at();

drop trigger if exists trg_user_preferences_updated_at on public.user_preferences;
create trigger trg_user_preferences_updated_at
before update on public.user_preferences
for each row execute function public.set_updated_at();

drop trigger if exists trg_bets_updated_at on public.bets;
create trigger trg_bets_updated_at
before update on public.bets
for each row execute function public.set_updated_at();

drop trigger if exists trg_deposit_requests_updated_at on public.deposit_requests;
create trigger trg_deposit_requests_updated_at
before update on public.deposit_requests
for each row execute function public.set_updated_at();

drop trigger if exists trg_limits_updated_at on public.limits;
create trigger trg_limits_updated_at
before update on public.limits
for each row execute function public.set_updated_at();

commit;
